// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uscclaqfturbbmsviwmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzY2NsYXFmdHVyYmJtc3Zpd21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjQ0MDUsImV4cCI6MjA1ODU0MDQwNX0.dBsbXMSxsYzU-zNr_mWQhX--bCp1MOOjIDKbFmVZKTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);